export const externalLinks = {
    tradeApp:'https://google.com',
    twitter: 'https://x.com',
    github: 'https://github.com',
    discord: 'https://discord.com',
    medium: 'https://medium.com',
    bridgeTechnology: '',
    liquidityMiningProgramTechnology: '',
    githubDevelopers: 'https://github.com',
    docsDevelopers: '',
    faucetDevelopers: '',
    termsOfUse: '',
    sequencers: '',
    fuelVM: '',
    defi: '',
    modular: '',
}
